### ISSUE TITLE
[Insight] Text files should end with a newline character - in .scrutinizer.yml, line 19

### ISSUE THREAD

**Issue by DarioSwain** [DarioSwain/ReCaptchaLibrary#8]
**[in .scrutinizer.yml, line 19](https://github.com/DarioSwain/ReCaptchaLibrary/blob/04b259a9b5d2db39a6fda782e4f597a6ab0ac593/.scrutinizer.yml#L19)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```
    override:
      -
        command: phpunit --coverage-clover=reCaptcha.clover
        coverage:
          file: reCaptcha.clover
          format: php-clover
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/cbc2c849-3910-4316-bac2-9977c4eda736/analyses/9)_
